apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg-preview
  namespace: app-preview
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80